// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-YMPAdn4-9bQuY0zaaPTCYINnwkVehs',
    appId: '1:1024151116492:web:770162f9bfc76a25188069',
    messagingSenderId: '1024151116492',
    projectId: 'oracle-diamond-02',
    authDomain: 'oracle-diamond-02.firebaseapp.com',
    storageBucket: 'oracle-diamond-02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgdksbfVdVQ1OM46UcxO-40ScjkNT8ng',
    appId: '1:1024151116492:android:98430f56c9927799188069',
    messagingSenderId: '1024151116492',
    projectId: 'oracle-diamond-02',
    storageBucket: 'oracle-diamond-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OP9VNo9AzrdD0-jAemvXMpmcVTQNDeE',
    appId: '1:1024151116492:ios:3277ff89389b6003188069',
    messagingSenderId: '1024151116492',
    projectId: 'oracle-diamond-02',
    storageBucket: 'oracle-diamond-02.appspot.com',
    iosClientId: '1024151116492-v4suvl2e2g9k4hfq1ranglb96rhqtuq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.oracleDiamond02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OP9VNo9AzrdD0-jAemvXMpmcVTQNDeE',
    appId: '1:1024151116492:ios:3277ff89389b6003188069',
    messagingSenderId: '1024151116492',
    projectId: 'oracle-diamond-02',
    storageBucket: 'oracle-diamond-02.appspot.com',
    iosClientId: '1024151116492-v4suvl2e2g9k4hfq1ranglb96rhqtuq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.oracleDiamond02',
  );
}
